name: Build Launcher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y wget gnupg software-properties-common
        sudo add-apt-repository -y ppa:beineri/opt-qt-6.7.0
        sudo apt-get update
        sudo apt-get install -y qt6base-dev qt6-tools-dev qt6-tools-dev-tools

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=/opt/qt6.7.0

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: NoVR-Launcher
        path: build
