name: Build Launcher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get -qq update && sudo apt-get install -y wget

    - name: Download and install Qt
      run: |
        wget https://download.qt.io/official_releases/qt/6.7/6.7.0/qt-opensource-linux-x64-6.7.0.run
        chmod +x qt-opensource-linux-x64-6.7.0.run
        ./qt-opensource-linux-x64-6.7.0.run --platform minimal --script qt-noninteractive.qs

    - name: Set up Qt environment
      run: |
        echo "/opt/Qt/6.7.0/gcc_64/bin" >> $GITHUB_PATH
        source /opt/Qt/6.7.0/gcc_64/bin/qt6-env.sh

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=/opt/Qt/6.7.0/gcc_64

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: NoVR-Launcher
        path: build
